# Generated by Django 3.2.4 on 2021-06-16 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
    ]
