# Generated by Django 3.2.4 on 2021-07-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_alter_post_imagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagecontent',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='content/'),
        ),
    ]
